<?php
$this->load->view('Plantillas/front_end/header');
$this->load->view('Plantillas/front_end/top');
$this->load->view('Plantillas/front_end/presentacion');
$this->load->view('Plantillas/front_end/lema');
$this->load->view('Plantillas/front_end/packs');
//$this->load->view('Dinamicas/'.$contenido);
$this->load->view('Plantillas/front_end/footer');
?>
